<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>
<body>
<?php
echo $block->Test();
?>

<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Content</th>
    </tr>
    <?php
        foreach ($block->getPostCollection() as $post){ 
            echo '<tr>
            <td>'.$post['id'].'</td>
            <td>'.$post['name'].'</td>
            <td>'.$post['content'].'</td>
          </tr>';
  }?>
  
</table>
</body>
</html>