<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" type="text/css" href="css/styles.css" media="all"> -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
    <title>Document</title>
</head>
<!-- <style>
text {
    color:blue;
}
</style> -->
<body>
<h2 class="text-color" style="text-align: center;"><strong>สิทธิพิเศษจากธนาคาร</strong></h2>
<table style="border-collapse: collapse; width: 100%;" border="0">
<tbody>
<tr>
<td style="width: 50%; text-align: right;"><a href="privilege"><img src="<?php echo $this->getViewFileUrl('images/01-banner7_tmntbank_sep20.png'); ?>" /></a></td>
<td style="width: 50%; text-align: left;"><img src="{{media url="02_KTC-BN10-OCT-re.png"}}" alt="" width="582" height="213"></td>
</tr>
<tr>
<td style="width: 50%; text-align: right;"><img style="float: right;" src="{{media url="01-banner7_tmntbank_sep20.png"}}" alt="" width="582" height="213"></td>
<td style="width: 50%; text-align: left;"><img src="{{media url="02-banner10_tmntbank_sep20.png"}}" alt="" width="582" height="213"></td>
</tr>
</tbody>
</table>
<table style="border-collapse: collapse; width: 100%;" border="0">
<tbody>
<tr>
<td style="width: 100%; text-align: center;"><img src="{{media url="04-KCC-OCT20-ALTEC.png"}}" alt="" width="582" height="213"></td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<h2 class="text-color2" style="text-align: center;"><strong>สิทธิพิเศษจากพาร์ทเนอร์</strong></h2>
<table style="border-collapse: collapse; width: 100%; height: 234px;" border="0">
<tbody>
<tr>
<td style="width: 50%; text-align: right;"><img src="{{media url="01-True_Banner_JUL20.jpg"}}" alt="" width="582" height="212"></td>
<td style="width: 50%;"><img src="{{media url="01-TMBWOW_Banner_JUL20.jpg"}}" alt="" width="582" height="212"></td>
</tr>
<tr>
<td style="width: 50%; text-align: right;"><img src="{{media url="Grab_2020-banner.jpg"}}" alt="" width="582" height="212"></td>
<td style="width: 50%;"><img src="{{media url="AW_PTT_Blue_Card_2020_banner-1.jpg"}}" alt="" width="582" height="212"></td>
</tr>
</tbody>
</table>
<table style="border-collapse: collapse; width: 100%;" border="0">
<tbody>
<tr>
<td style="width: 100%; text-align: center;"><img src="{{media url="01-TQM_Banner_JUL20.jpg"}}" alt="" width="582" height="212"></td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<h2 class="text-color3" style="text-align: center;"><strong>พาร์ทเนอร์ของเรา</strong></h2>
<table style="border-collapse: collapse; width: 100%;" border="0">
<tbody>
<tr>
<td style="width: 25%; text-align: center;"><img src="{{media url="logo_Kasisorn.png"}}" alt="" width="250" height="95"></td>
<td style="width: 25%; text-align: center;"><img src="{{media url="logo_KrungSri.png"}}" alt="" width="250" height="95"></td>
<td style="width: 25%; text-align: center;"><img src="{{media url="scb.png"}}" alt="" width="250" height="95"></td>
<td style="width: 25%; text-align: center;"><img src="{{media url="ktc-new.jpg"}}" alt="" width="250" height="92"></td>
</tr>
</tbody>
</table>
    <button type="button" class="btn btn-danger">Danger</button>
</body>
</html>